name: Node.js CI
on: [push]
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./application-tracker
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
        working-directory:  ${{env.working-directory}}
      - run: npm run build --if-present
        working-directory:  ${{env.working-directory}}
      - run: npm test:unit
        working-directory:  ${{env.working-directory}}
      - run: npm lint
        working-directory:  ${{env.working-directory}}

